version: '3'

services:
  adminservice:
    image: adminservice
    build:
      context: ./AdminService
      dockerfile: Dockerfile
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - webnet
networks:
  webnet:
